# 1.0.2.1
# created: 05 Feb 2022
# updated: 18 Mar 2022
# Create Indexes from Markdown
# https://github.com/DaanV2/Markdown-Action-Create-Indexes

name: Create markdown indexes

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DaanV2/Markdown-Action-Create-Indexes@v1.6.0
        with: 
          folder: ${{github.workspace}}/docs/

      - name: Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "Bot@Example.com"
          git config --global user.name "DaanV2 Bot"
          git add .
          git commit -m "auto: Generated markdown indexes"
          git push
