# 1.1.1.0
# created: 05 Feb 2022
# updated: 28 May 2023
# update checkout to main
# update checkout to v3.0.2
# Create Indexes from Markdown
# https://github.com/DaanV2/Markdown-Action-Create-Indexes

name: Create markdown indexes

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #  Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

# Runs a single command using the runners shell
      - uses: DaanV2/Markdown-Action-Create-Indexes@main
        with: 
          folder: ${{github.workspace}}/docs/
          filename: index.md

      - name: Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "39887717+zer0Kerbal@users.noreply.github.com"
          git config --global user.name "zer0Kerbal"
          git add .
          git commit -m "auto: Generated markdown indexes"
          git push
